name: CI

on:
  pull_request:
    branches: [ dev ]

jobs:

  test:                 # ← Первый job
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run test
        run: echo "Tests passed"

  notify:               # ← Второй job (на одном уровне с test)
    needs: test
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Send Telegram message
        run: |
          STATUS="${{ needs.test.result }}"
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TG_BOT_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TG_CHAT_ID }} \
          -d text="PR #${{ github.event.pull_request.number }} status: ${STATUS}"
